#!/bin/sh
set -e

export PATH="/usr/bin:$PATH"

if [ -s "$HOME/.nvm/nvm.sh" ]; then
  . "$HOME/.nvm/nvm.sh"
  nvm use --silent
fi

node scripts/prevent-main-commit.js
node scripts/update-package-lock.js
npx lint-staged --config lint-staged.config.mjs
npm run check:generated
